# COMMON APPLICATION PROPERTIES

# start services on random port by default
server.port: 0

# database init, supports mysql too
petclinic.database: mysql

spring:
  datasource:
    schema: classpath*:db/${petclinic.database}/schema.sql
    data: classpath*:db/${petclinic.database}/data.sql
    url:  jdbc:mysql://localhost:3306/petclinic?useUnicode=true
  sleuth:
    sampler:
      percentage: 1.0

spring.datasource.username: root 
spring.datasource.password: 123 
spring.datasource.driver-class-name: com.mysql.jdbc.Driver 
spring.datasource.driverClassName: com.mysql.jdbc.Driver
spring.jpa.database: MYSQL 
spring.jpa.database-platform: org.hibernate.dialect.MySQLDialect
spring.datasource.initialize: true
# JPA
spring.jpa.hibernate.ddl-auto: none

# Spring Boot 1.5 makes actuator secure by default
management.security.enabled: false

# Logging
logging.level.org.springframework: TRACE
